frame = gdb.selected_frame()
r1 = frame.read_register("a2")
r2 = frame.read_register("x12")
r3 = frame.read_register("pc")
r4 = frame.read_register("ra")
r5 = frame.read_register("sp")
r6 = frame.read_register("a1")
print("a2", r1.format_string(format='x'))
print("x12", r2)
print("pc", r3)
print("ra", r4)
print("sp", r5)
print("a1", r6.format_string(format='z'))
